Repository codeit-sprint-fullstack/3-sprint-mission-be, pull requests merged in 2024-11, with the labels that each got.

#15 [하신혜] Sprint 6
  .gitignore
  package-lock.json
  package.json
  product-api/app.js
  product-api/env.js
  product-api/models/product.js
  product-api/package-lock.json
  product-api/package.json
  product-api/routes/productRoutes.js
  product-api/server.js
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/footer.css
  src/components/footer.js
  src/components/header.css
  src/components/header.js
  src/components/icons/ic_facebook.png
  src/components/icons/ic_instagram.png
  src/components/icons/ic_search.png
  src/components/icons/ic_twitter.png
  src/components/icons/ic_youtube.png
  src/components/icons/img_default.svg
  src/components/icons/panda_face.png
  src/components/img/Img_home_01.png
  src/components/img/Img_home_02.png
  src/components/img/Img_home_03.png
  src/components/img/Img_home_bottom.png
  src/components/img/Img_home_top.png
  src/components/items.css
  src/components/items.js
  src/components/landingpage.css
  src/components/landingpage.js
  src/components/mainpage/login.css
  src/components/mainpage/login.js
  src/components/productRegistration.css
  src/components/productRegistration.js
  src/fonts/._ROKAF Sans Bold.ttf
  src/fonts/ROKAF Sans Medium.ttf
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 제출일 이후 제출한PR, 최종 제출

#13 [배진한] Sprint6
  .gitignore
  app.js
  models/Product.js
  package-lock.json
  package.json
  sprint6/data/mock.js
  sprint6/data/seed.js
  sprint6/request.http
Labels: 매운맛🔥, 최종 제출

#5 [함헌규] sprint6
  .eslintrc.json
  .gitignore
  .prettierrc
  docs/sprint6.md
  package-lock.json
  package.json
  src/app.ts
  src/constants/messages.ts
  src/constants/queryOptions.ts
  src/models/product.ts
  src/routes/Products/Controller.ts
  src/routes/Products/service.ts
  src/types/asyncRequestHandler.ts
  src/types/product.ts
  src/utils/asyncRequestHandler.ts
  src/utils/struct.ts
  tsconfig.json
Labels: 매운맛🔥, 최종 제출

#16 [이현우] sprint6
  .gitignore
  JOURNAL.md
  app.js
  constants/message.js
  data/mock.js
  data/seed.js
  models/Product.js
  package.json
  pnpm-lock.yaml
  routes/index.js
  routes/products/controller.js
  routes/products/service.js
  util.js
Labels: 매운맛🔥, 제출일 이후 제출한PR, 최종 제출

#8 [임예지] Sprint 6
  .gitignore
  package-lock.json
  package.json
  product-express/.gitignore
  product-express/app.js
  product-express/models/product.js
  product-express/package-lock.json
  product-express/package.json
Labels: 매운맛🔥

#7 [강수정] sprint6
  back/.gitignore
  back/app.js
  back/data/mock.js
  back/data/seed.js
  back/models/Good.js
  back/models/Product.js
  back/models/Task.js
  back/package-lock.json
  back/package.json
  back/request.http
Labels: 매운맛🔥, 최종 제출

#14 [정유석] Sprint6
  .gitignore
  app.js
  data/seed.js
  models/Product.js
  package.json
  routes/products.js
Labels: 순한맛🐑, 진행 중 🏃

#21 [박수환] Sprint7
  .gitignore
  app.js
  article.http
  package-lock.json
  package.json
  prisma/migrations/20241106071538_schema_1/migration.sql
  prisma/migrations/20241107004823_/migration.sql
  prisma/migrations/20241111004914_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  router/articleRouter.js
  router/commentRouter.js
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#22 [sprint7] 전준기
  sprint7/.gitignore
  sprint7/app.js
  sprint7/package-lock.json
  sprint7/package.json
  sprint7/prisma/schema.prisma
Labels: 매운맛🔥, 미완성🫠, 제출일 이후 제출한PR

#18 [배진한] Sprint7
  sprint7/.gitignore
  sprint7/app.js
  sprint7/docs/sprint7.md
  sprint7/http/articles.http
  sprint7/http/comment.http
  sprint7/http/products.http
  sprint7/orderByFunction.js
  sprint7/package-lock.json
  sprint7/package.json
  sprint7/prisma/migrations/20241116061602_add_product_email/migration.sql
  sprint7/prisma/migrations/20241116094525_remove_product_email/migration.sql
  sprint7/prisma/migrations/20241116130153_add_product_likes/migration.sql
  sprint7/prisma/migrations/20241116131817_add_product_likes/migration.sql
  sprint7/prisma/migrations/20241116155152_add_product_likes_opptional/migration.sql
  sprint7/prisma/migrations/20241116174703_add_comment_model/migration.sql
  sprint7/prisma/migrations/20241117113216_add_aritcle_likes/migration.sql
  sprint7/prisma/migrations/20241117144233_add_comment_product_opptional/migration.sql
  sprint7/prisma/migrations/20241117145605_add_comment_likes/migration.sql
  sprint7/prisma/migrations/migration_lock.toml
  sprint7/prisma/mocks/articlesMock.js
  sprint7/prisma/mocks/commentsMock.js
  sprint7/prisma/mocks/productsMock.js
  sprint7/prisma/schema.prisma
  sprint7/prisma/seed.js
  sprint7/structs.js
Labels: 순한맛🐑, 최종 제출

#4 [배진한] Sprint4 node (part1)
  .gitignore
  apies/ArticleService.js
  apies/ProductService.js
  apies/main.js
  apies/package-lock.json
  apies/package.json
Labels: 매운맛🔥, 최종 제출
